name: Click分享Link
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9,14,18 * * *' 
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # ✅ 从 v2 升级为 v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4  # ✅ 从 v1 升级为 v4
        with:
          node-version: 18  # ✅ 固定 Node 版本，避免 .nvmrc 报错

      - name: Cache node_modules
        uses: actions/cache@v4  # ✅ 从 v2 升级为 v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: npm install
        run: |
          npm install

      - name: '运行'
        run: |
          node momo_random.js
        env:
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          QYWX_AM: ${{ secrets.QYWX_AM }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}