name: Click分享Link

on:
  push:
    branches:
      - main
  schedule:
    - cron: '1,32 * * * *'
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 自动检测 Node.js 版本（支持 .nvmrc 或 package.json 中的 engines.node 字段）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'  # 若仓库中无此文件，可自动回退到默认 Node 版本
          cache: 'npm'                 # ✅ 内置 npm 缓存，自动识别 package-lock.json

      # 安装依赖（npm 自动命中缓存）
      - name: Install dependencies
        run: npm ci || npm install     # 优先使用 npm ci（更快、更干净），失败则回退到 install

      # 运行脚本
      - name: 运行
        run: node momo_random.js
        env:
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          QYWX_AM: ${{ secrets.QYWX_AM }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}